name: CD - TestFlight Deployment

on:
  push:
    branches:
      - main
      - release/*

jobs:
  testflight-deploy:
    name: Deploy to TestFlight
    runs-on: macos-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout source code
        uses: actions/checkout@v2

      # Paso 2: Configurar Xcode
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.3.1"

      # Paso 3: Configurar Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      # Paso 4: Instalar Fastlane
      - name: Install Fastlane
        run: gem install fastlane

      # Paso 5: Configurar claves de acceso para App Store Connect
      - name: Configure App Store Connect API Key
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_JSON: ${{ secrets.APP_STORE_CONNECT_API_KEY_JSON }}

      # Paso 6: Ejecutar la lane de Fastlane para TestFlight
      - name: Run Fastlane Beta Lane
        run: fastlane beta
